import subprocess
import json
import os
from crewai.tools import tool

class CostEstimator:
    def __init__(self, binary_path="infracost.exe"):
        self.binary_path = os.path.abspath(binary_path)

    @tool
    def get_monthly_cost(directory_path: str) -> str:
        """
        Runs infracost breakdown on the target directory and returns a cost summary.
        Args:
            directory_path (str): Path to the terraform workspace.
        """
        estimator = CostEstimator()
        result = estimator._execute_infracost(directory_path)
        return estimator.format_report(result)

    @tool
    def generate_financial_report(project_slug: str) -> str:
        """
        Generates a detailed FINANCIAL_REPORT.md file in the project workspace.
        Args:
            project_slug (str): The slug identifying the workspace.
        """
        directory_path = os.path.join("output", project_slug)
        estimator = CostEstimator()
        result = estimator._execute_infracost(directory_path)
        
        if "error" in result:
            return f"Failed to generate report: {result['details']}"
            
        report_content = estimator._build_markdown_report(result)
        report_path = os.path.join(directory_path, "FINANCIAL_REPORT.md")
        
        try:
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(report_content)
            return f"Financial report generated successfully at {report_path}"
        except Exception as e:
            return f"Error writing report: {str(e)}"

    def _execute_infracost(self, directory_path):
        if not os.path.exists(directory_path):
            return {"error": "PATH_NOT_FOUND", "details": f"Directory {directory_path} does not exist."}

        try:
            # infracost breakdown --path <dir> --format json
            result = subprocess.run(
                [self.binary_path, "breakdown", "--path", directory_path, "--format", "json"],
                capture_output=True,
                text=True,
                shell=True
            )
            
            if result.returncode != 0:
                error_msg = result.stderr or result.stdout or "Unknown Infracost error"
                if "INFRACOST_API_KEY" in error_msg or "auth login" in error_msg:
                    return {"error": "AUTHENTICATION_REQUIRED", "details": "Infracost requires an API key."}
                return {"error": "INFRACOST_ERROR", "details": error_msg}

            data = json.loads(result.stdout)
            
            return {
                "total_monthly_cost": data.get("totalMonthlyCost", "0.00"),
                "currency": data.get("currency", "USD"),
                "projects": data.get("projects", []),
                "passed": True
            }

        except Exception as e:
            return {"error": "EXCEPTION", "details": str(e)}

    def _build_markdown_report(self, result):
        cost = result["total_monthly_cost"]
        currency = result["currency"]
        
        report = f"# 💸 Financial Cost Report\n\n"
        report += f"**Estimated Total Monthly Cost:** `{cost} {currency}`\n\n"
        report += "## 🏗️ Resource Breakdown\n\n"
        report += "| Resource Name | Monthly Cost | Currency |\n"
        report += "| :--- | :--- | :--- |\n"
        
        for proj in result.get("projects", []):
            res_breakdown = proj.get("breakdown", {}).get("resources", [])
            for res in res_breakdown:
                r_cost = res.get("monthlyCost", "0.00")
                if r_cost != "0.00":
                    report += f"| {res.get('name')} | {r_cost} | {currency} |\n"
        
        report += "\n---\n*Report generated by Terraform AI Agent (FinOps Module)*"
        return report

    def format_report(self, cost_result):
        if "error" in cost_result:
            return f"Cost Estimation Error: {cost_result['details']}"

        cost = cost_result["total_monthly_cost"]
        currency = cost_result["currency"]
        
        report = f"PROJECTED MONTHLY COST: {cost} {currency}\n"
        report += "Top Cost Drivers found. Detailed report available in FINANCIAL_REPORT.md."
        return report
